"""
Persona Service Core - Layer 2: LLM Identity Seed Generation
这是 v5.0 的核心创新：让 LLM 创造性生成身份种子，而不是从词库采样

Reference: 档案设计文档 §1.4.1
"""
from typing import Dict, List, Optional
import json
from dataclasses import dataclass


@dataclass
class IdentitySeed:
    """Layer 2 output: Identity seed generated by LLM"""
    name: str
    birth_place: str
    family_structure_type: str
    core_personality_seed: str
    unique_life_seed: str  # One influential early experience
    generated_by: str = "llm"
    # Gender implied by the name ("男"/"女"). Single source of truth so the
    # archive D1 gender and the top-level M/F flag stay consistent with the
    # name; empty means "unknown" and is resolved downstream.
    gender: str = ""


class IdentitySeedGenerator:
    """
    Layer 2: LLM-based identity seed generation
    
    Takes L1 skeleton (parameter constraints) → generates unique identity seeds
    Temperature: 0.9-1.1 (high diversity)
    Batch size: 8-10 per call (cost efficiency)
    """
    
    @staticmethod
    def get_identity_seed_prompt(skeleton: Dict, batch_size: int = 8) -> str:
        """
        Generate prompt for LLM identity seed generation
        
        Skeleton provides constraints, LLM fills with creativity
        """
        prompt = f"""基于以下参数约束，为 {batch_size} 个虚拟初二学生生成唯一的身份种子。

【参数骨架约束】
- 年级: 初二 (Grade 8)
- 先验知识水平: {skeleton.get('p_know', 0.5)}（0-1 scale）
- 学习率: {skeleton.get('p_learn', 0.25)}
- 主要误概念类型: {skeleton.get('misconception_type', '代数')}
- 主要个性倾向: {skeleton.get('personality_type', '内向')}
- 家庭 SES 水平: {skeleton.get('ses_level', '中等')}
- 来自地理区域: {skeleton.get('region', '县城')}

【生成要求】
1. 每个学生必须有**显著不同**的身份背景（不能有重复的名字、背景、经历主题）
2. 避免套路化人设（如"小明""张伟"等通用名字）
3. 每个身份包含**至少一个长尾特征**（如：左撇子、养爬虫宠物、父母是货车司机）
4. 家庭背景要有细节（具体到区县、父母具体职业、家庭结构等）
5. 独特的早期经历要有具体细节、有逻辑地影响当前学习态度

【输出格式】
返回一个 JSON 数组，包含 {batch_size} 个对象，每个对象包含：
{{
  "name": "独特的中文名字",
  "gender": "男 或 女（必须与名字的气质一致，不要给男生起女性化名字、给女生起男性化名字）",
  "birth_place": "具体到区县的出生地",
  "family_structure_type": "完整家庭 | 单亲 | 留守 | 重组",
  "core_personality_seed": "一句话描述核心人格倾向",
  "unique_life_seed": "一个有细节的影响学习态度的早期经历（2-3句话）"
}}

开始生成：
"""
        return prompt
    
    @staticmethod
    def parse_llm_output(llm_response: str) -> List[IdentitySeed]:
        """
        Parse LLM JSON response into IdentitySeed objects
        """
        try:
            data = json.loads(llm_response)
            if isinstance(data, list):
                seeds = []
                for item in data:
                    seed = IdentitySeed(
                        name=item.get("name", ""),
                        birth_place=item.get("birth_place", ""),
                        family_structure_type=item.get("family_structure_type", "完整家庭"),
                        core_personality_seed=item.get("core_personality_seed", ""),
                        unique_life_seed=item.get("unique_life_seed", ""),
                        gender=item.get("gender", "")
                    )
                    seeds.append(seed)
                return seeds
            else:
                # Single object
                item = data
                return [IdentitySeed(
                    name=item.get("name", ""),
                    birth_place=item.get("birth_place", ""),
                    family_structure_type=item.get("family_structure_type", "完整家庭"),
                    core_personality_seed=item.get("core_personality_seed", ""),
                    unique_life_seed=item.get("unique_life_seed", ""),
                    gender=item.get("gender", "")
                )]
        except json.JSONDecodeError:
            return []


class Layer1SkeletonGenerator:
    """
    Layer 1: Random skeleton from calibrated posterior
    
    Takes posterior from real data BKT fit → samples parameter distribution
    """
    
    @staticmethod
    def sample_skeleton(posterior_dist: Dict) -> Dict:
        """
        Sample a skeleton from posterior distribution
        
        Args:
            posterior_dist: Calibrated posterior from real data fitting
                           e.g., {"p_know": {"mu": 0.3, "sigma": 0.15}, ...}
        
        Returns:
            Skeleton dict with sampled parameters
        """
        import numpy as np
        
        skeleton = {}
        
        # Sample p_know (prior knowledge)
        if "p_know" in posterior_dist:
            mu, sigma = posterior_dist["p_know"]["mu"], posterior_dist["p_know"]["sigma"]
            skeleton["p_know"] = float(np.clip(np.random.normal(mu, sigma), 0.0, 1.0))
        else:
            skeleton["p_know"] = 0.3
        
        # Sample learning-related parameters
        if "p_learn" in posterior_dist:
            mu, sigma = posterior_dist["p_learn"]["mu"], posterior_dist["p_learn"]["sigma"]
            skeleton["p_learn"] = float(np.clip(np.random.normal(mu, sigma), 0.05, 0.5))
        else:
            skeleton["p_learn"] = 0.25
        
        # Map p_know to personality type (constraint)
        if skeleton["p_know"] < 0.2:
            skeleton["personality_type"] = "低自信"
        elif skeleton["p_know"] < 0.5:
            skeleton["personality_type"] = "中等自信"
        else:
            skeleton["personality_type"] = "自信"
        
        # Add other fixed constraints
        skeleton["region"] = "县城"  # From config
        # Sample family SES from a realistic county-town distribution instead of
        # hard-coding "中等", so student/family backgrounds -- and the parent
        # personas derived from them -- span the full 低/中等/高 range.
        skeleton["ses_level"] = np.random.choice(
            ["低", "中等", "高"], p=[0.25, 0.55, 0.20])
        skeleton["misconception_type"] = "代数"
        
        return skeleton
